export const categories = [
    "Personal Assistants",
    "Voice Recognition",
    "Image Recognition",
    "Natural Language Processing",
    "Sentiment Analysis",
    "Translation Services",
    "Virtual Reality",
    "Augmented Reality",
    "Speech Synthesis",
    "Machine Learning",
    "Deep Learning",
    "Robotics",
    "Autonomous Vehicles",
    "Medical Diagnosis",
    "Genomics",
    "Biometrics",
    "Facial Recognition",
    "Gesture Recognition",
    "Emotion Detection",
    "Content Recommendation",
    "Predictive Analytics",
    "Supply Chain Optimization",
    "Fraud Detection",
    "Financial Forecasting",
    "Algorithmic Trading",
    "Customer Relationship Management",
    "Human Resources Management",
    "Recruitment",
    "Talent Management",
    "Learning Management Systems",
    "Employee Engagement",
    "Sales Analytics",
    "Marketing Automation",
    "Social Media Analytics",
    "Advertising Technology",
    "Email Marketing",
    "Search Engine Optimization",
    "Content Management",
    "E-commerce",
    "Online Marketplaces",
    "Payment Processing",
    "Cryptocurrency",
    "Blockchain",
    "Internet of Things",
    "Smart Homes",
    "Wearable Technology",
    "Health Monitoring",
    "Fitness Tracking",
    "Electronic Health Records",
    "Telemedicine",
    "Clinical Trials",
    "Drug Discovery",
    "Bioinformatics",
    "Climate Science",
    "Weather Forecasting",
    "Renewable Energy",
    "Energy Storage",
    "Smart Grids",
    "Agriculture Technology",
    "Crop Monitoring",
    "Precision Agriculture",
    "Food Safety",
    "Supply Chain Traceability",
    "Water Management",
    "Waste Management",
    "Recycling Technology",
    "Sustainable Development",
    "Smart Cities",
    "Urban Planning",
    "Transportation",
    "Traffic Management",
    "Public Safety",
    "Surveillance",
    "Emergency Response",
    "Disaster Recovery",
    "Cybersecurity",
    "Network Security",
    "Data Privacy",
    "Identity Management",
    "Access Control",
    "Threat Detection",
    "Incident Response",
    "Risk Management",
    "Compliance",
    "Governance",
    "Legal Technology",
    "Document Management",
    "Contract Management",
    "Intellectual Property",
    "Patent Analysis",
    "Regulatory Technology",
    "Tax Technology",
    "Accounting Technology",
    "Financial Planning",
    "Budgeting",
    "Investment Management",
    "Wealth Management",
    "Insurance Technology",
    "Claims Processing",
    "Underwriting",
    "Policy Management",
    "Risk Assessment",
    "Customer Experience",
    "User Experience Design",
    "Product Design",
    "Prototyping",
    "A/B Testing",
    "Usability Testing",
    "Feedback Analysis",
    "Journey Mapping",
    "Customer Feedback",
    "Customer Support",
    "Helpdesk Systems",
    "Live Chat",
    "Chatbots",
    "Knowledge Management",
    "Ticketing Systems",
    "Remote Support",
    "Virtual Events",
    "Video Conferencing",
    "Webinars",
    "Online Courses",
    "Learning Platforms",
    "Professional Development",
    "Certifications",
    "Skill Development",
    "Mentorship",
    "Collaboration Tools",
    "Project Management",
    "Task Management",
    "Time Tracking",
    "Resource Management",
    "Workforce Management",
    "Performance Management",
    "Compensation Management",
    "Benefits Administration",
    "Employee Wellness",
    "Diversity and Inclusion",
    "Employee Recognition",
    "Workplace Safety",
    "Facility Management",
    "Space Planning",
    "Asset Management",
    "Maintenance Management",
    "Lease Management",
    "Energy Management",
    "Environmental Monitoring",
    "Fleet Management",
    "Logistics",
    "Warehouse Management",
    "Inventory Management",
    "Order Management",
    "Supplier Management",
    "Procurement",
    "Contract Management",
    "Spend Analysis",
    "Sourcing",
    "Category Management",
  ];
  